apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: car-info-service
  name: car-info-service
  namespace: carmarketplace-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-info-service
  template:
    metadata:
      labels:
        app: car-info-service
    spec:
      containers:
        - name: cm-car-info-service
          image: geekymon2/cm-car-info-svc:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
          - name: ARTIFACT_NAME
            value: "car-info-service"
          - name: CARINFO_DB_NAME
            value: "carinfodbci"
          - name: TZ
            value: "Australia/Sydney"
          - name: SPRING_PROFILES_ACTIVE
            value: "ci"
          - name: CARINFO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: carinfodbpassword
                key: carinfodbpassword
          - name: JWT_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: jwtauthsecret
                key: jwtauthsecret                