apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: carmarketplace-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: cm-user-service
          image: geekymon2/cm-user-svc:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
          - name: ARTIFACT_NAME
            value: "user-service"
          - name: USER_DB_NAME
            value: "userdbci"
          - name: TZ
            value: "Australia/Sydney"
          - name: SPRING_PROFILES_ACTIVE
            value: "ci"
          - name: USER_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: userdbpassword
                key: userdbpassword
          - name: JWT_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: jwtauthsecret
                key: jwtauthsecret